name: Plugin Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Vulnerability Scanner Action on a Plugin
    steps:
      - uses: actions/checkout@v3
      - name: Download and test a plugin
        run: |
          svn co https://plugins.svn.wordpress.org/progress-bar/trunk/ ./progress-bar
      - uses: ./
        with:
          api-provider: wordfence
          api-token: ''
          type: plugin
          name: progress-bar
