name: Test Vulnerability Scanner Action on a Plugin
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Vulnerability Scanner Action on a Plugin
    steps:
      - uses: actions/checkout@v3
      - name: Download and test a plugin
        run: |
          svn co https://plugins.svn.wordpress.org/progress-bar/trunk/ ./progress-bar
      - uses: ./
        with:
          api-provider: wordfence
          api-token: ''
          type: plugin
          name: progress-bar
      - name: Download and test a theme
        run: |
          svn co https://themes.svn.wordpress.org/twentytwentyone/1.8/ ./twentytwentyone
      - uses: ./
        with:
          api-provider: wordfence
          api-token: ''
          type: theme
          name: twentytwentyone
